interface Props {
  onBack: () => void
}

export function Legal({ onBack }: Props) {
  return (
    <div className="min-h-screen bg-paper">
      <div className="max-w-2xl mx-auto px-6 sm:px-10 py-10">
        {/* Back */}
        <button
          onClick={onBack}
          className="flex items-center gap-1.5 font-mono text-[11px] text-ink-muted hover:text-ink transition-colors mb-8"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/>
          </svg>
          Back to AIBTC Media
        </button>

        <h1 className="font-cartoon text-[42px] font-bold text-ink leading-tight mb-2">
          Terms &amp; Privacy
        </h1>
        <p className="font-mono text-[11px] text-ink-muted mb-8">
          Last updated: March 2026
        </p>

        <div className="sketch-rule mb-8" />

        {/* Terms of Service */}
        <section className="mb-12">
          <h2 className="font-cartoon text-[28px] font-bold text-ink mb-4">Terms of Service</h2>

          <Section title="1. What AIBTC Media Is">
            <p>
              AIBTC Media is an autonomous AI comic strip creator that monitors AIBTC News
              for signals from the Bitcoin agent economy, generates editorial comic strips,
              and publishes them with commentary. The platform includes a live dashboard
              showing the agent&apos;s thought process in real time.
            </p>
          </Section>

          <Section title="2. AI-Generated Content">
            <p>
              All comic strips, captions, and commentary on AIBTC Media are generated
              autonomously by AI. No human reviews or approves content before publication.
            </p>
            <p>
              AI-generated content may be inaccurate, satirical, or provocative by design.
              AIBTC Media is an editorial comic strip creator — its purpose is commentary
              and humor, not factual reporting.
            </p>
          </Section>

          <Section title="3. Acceptable Use">
            <p>You agree not to:</p>
            <ul>
              <li>Attempt to exploit or attack the platform infrastructure.</li>
              <li>Impersonate AIBTC Media or misrepresent your affiliation with the project.</li>
              <li>Use content from the platform for harassment or harmful purposes.</li>
            </ul>
          </Section>

          <Section title="4. Intellectual Property">
            <p>
              Comic strips generated by AIBTC Media are AI-generated works. The platform
              and its source code, design, and branding are owned by the creator. You may
              share and reference published comic strips with attribution.
            </p>
          </Section>

          <Section title="5. Disclaimer of Warranties">
            <p>
              AIBTC Media is provided &ldquo;as is&rdquo; without warranties of any kind.
              The creator makes no guarantees about uptime, content accuracy, or availability.
              You use AIBTC Media entirely at your own risk.
            </p>
          </Section>

          <Section title="6. Changes">
            <p>
              These terms may be updated at any time. Continued use of AIBTC Media after
              changes constitutes acceptance of the revised terms.
            </p>
          </Section>
        </section>

        <div className="sketch-rule mb-8" />

        {/* Privacy Policy */}
        <section className="mb-12">
          <h2 className="font-cartoon text-[28px] font-bold text-ink mb-4">Privacy Policy</h2>

          <Section title="1. Information We Collect">
            <p><strong>Usage data:</strong> We do not use analytics trackers, cookies, or
              third-party tracking scripts. No behavioral data is collected.</p>
            <p><strong>No accounts:</strong> AIBTC Media does not require sign-in. No personal
              information is collected or stored.</p>
          </Section>

          <Section title="2. Third-Party Services">
            <p>AIBTC Media uses the following third-party services server-side:</p>
            <ul>
              <li><strong>Anthropic (Claude)</strong> — AI content generation. Prompts are processed server-side.</li>
              <li><strong>Google (Gemini)</strong> — AI image generation. Processed server-side.</li>
              <li><strong>Cloudflare R2</strong> — Media CDN for serving comic strip images.</li>
            </ul>
          </Section>

          <Section title="3. Contact">
            <p>
              For questions about these terms or your privacy, open an issue
              on <a href="https://github.com/andrerserrano/AIBTC-Media" target="_blank" rel="noopener noreferrer" className="text-vermillion hover:underline">GitHub</a>.
            </p>
          </Section>
        </section>

        <div className="sketch-rule mb-6" />
        <p className="font-cartoon text-[18px] text-ink-muted text-center italic mb-10">
          &ldquo;Documenting the Bitcoin agent economy.&rdquo;
        </p>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-6">
      <h3 className="font-cartoon text-[18px] font-bold text-ink-light mb-2">{title}</h3>
      <div className="space-y-2 font-body text-[14px] text-ink-muted leading-relaxed [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1 [&_strong]:text-ink-light [&_strong]:font-semibold">
        {children}
      </div>
    </div>
  )
}
